### ISSUE TITLE
Does it support application-wide counter?

### ISSUE THREAD

**Issue by thorichelli** [falemagn/fameta-counter#1]
I think, the counter starts from the first value at the beginning of each new translation unit, is it possible to use an incrementing counter application-wide? I want to have unique values between translation units either. 
Do you think __FILE__ macro (converted to an int value, in compile-time) helps?

**Comment by falemagn** [comment]
> I think, the counter starts from the first value at the beginning of each new translation unit, is it possible to use an incrementing counter application-wide? I want to have unique values between translation units either.
> Do you think **FILE** macro (converted to an int value, in compile-time) helps?

This being a constexpr value, cannot be incremented across translation units as far as I am aware of.

What are you trying to achieve? Maybe there's another way.

**Comment by 9inefold** [comment]
You run the risk of ODR violations doing this... what order should it be evaluated in? If I increment the counter in ``header.hpp`` and then again in ``main.cpp``, which one should happen first? It's UB and should be avoided at all costs.

**Comment by thorichelli** [comment]
Already addressed this using templates, constexpr filename hash calculation two years ago. Thanks.
